version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  ui:
    build:
      context: ./ui
    ports:
      - "3000:3000" # Map React app's port 3000 to host port 3000
    depends_on:
      - backend
