GET http://localhost:8000/

###
GET http://localhost:8000/hardware

###
POST http://localhost:8000
Content-Type: application/json

{
    "name": "Val",
    "location": "Vancouver"
}
###
GET http://localhost:8000/users
Content-Type: application/json
###
GET http://localhost:8000/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJuZXd1c2VyIiwiaWF0IjoxNjk3OTM4NjMyfQ.UNAdQft4H9rApa0wbWNcpNfUA3gnQov7_c4_eWNCEsY

### Create User ###
POST http://localhost:8000/register
Content-Type: application/json

{
  "username": "newuser",
  "password": "password123"
}
### User Login ###
POST http://localhost:8000/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "password123"
}